name: crrwoq

on:
  release:
    # Only use the types keyword to narrow down the activity types that will trigger your workflow.
    types: [published, created, edited]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.6
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f ./script/requirements.txt ]; then pip install -r ./script/requirements.txt; fi
      - name: Crawler
        run: |
          python ./script/update_original.py
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
